// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Use DIRECT_URL (unpooled Neon endpoint) for migrations.
    // Falls back to DATABASE_URL for environments without a separate direct URL.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
